# This file is autogenerated with reference to tests/template_experiment_tests/test.py

# To run this test in PyCharm, right click on the source code and click either
# "Run 'pytest' in test.py" or "Debug 'pytest' in test.py".
#
# Normal run mode is fastest and gives the most comprehensive logs.
# Debug run mode is slower, but drops into the debugger when an error occurs during the main experiment,
# which can be very useful for debugging.
#
# Make sure you close any pre-existing debug sessions before running the tests.
#
# You can customize the behavior of the automated tests by overriding certain methods within
# your experiment class, located in experiment.py:
# - test_experiment
# - test_create_bots
# - test_run_bots
# - test_check_bots
# - test_check_bot

import os

import pytest

pytest_plugins = ["pytest_dallinger", "pytest_psynet"]
experiment_dir = os.path.dirname(__file__)


@pytest.mark.parametrize("experiment_directory", [experiment_dir], indirect=True)
def test_experiment(launched_experiment):
    launched_experiment.test_experiment()
