#!/bin/bash

set -euo pipefail

docker run \
  --rm \
  -v "${PWD}":/experiment \
  -e SKIP_DEPENDENCY_CHECK="" \
  registry.gitlab.com/psynetdev/psynet:v12.1.1 \
  bash -c "cd /experiment && psynet generate-constraints"
