#!/bin/bash

set -euo pipefail

. docker/params

if [[ ${PSYNET_DEVELOPER_MODE:-} == "1" ]]; then
  . docker/check-dev-installations
fi

. docker/services
. docker/build

( docker stop dallinger > /dev/null && echo Stopped existing dallinger container && \
  docker rm dallinger ) 2>/dev/null || true


# Removing this seems to be important for allowing Docker images to be built within Docker.
# Otherwise the user doens't have Docker privileges.
#-u $(id -u "${USER}"):$(id -g "${USER}") \
#
# Once this is removed, we needed to replace this:
# -v "${HOME}/Library/Application Support/dallinger/":/.local/share/dallinger/ \
#
# with this:
# -v "${HOME}/Library/Application Support/dallinger/":/root/.local/share/dallinger/ \
#
#
# Note: SSH deployment currently only works on Mac.
# To fix this we need to sort out the SSH mapped volume and the application data mapped volume.
# Attempts already exist in docker/params but they need testing.

docker run \
  --name dallinger \
  --rm \
  -ti \
  -v /etc/group:/etc/group \
  -v ~/.docker:/root/.docker \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "${SSH_VOLUME}" \
  -v "${HOME}/Library/Application Support/dallinger/":/root/.local/share/dallinger/ \
  -v "${PWD}":/experiment \
  -v "${HOME}"/.dallingerconfig:/root/.dallingerconfig \
  -v "$PSYNET_EXPORT_STORAGE":/psynet-data/export \
  -v ~/.ssh:/root/.ssh \
  --network dallinger \
  -p 5000:5000 \
  -e SKIP_DEPENDENCY_CHECK=1 \
  -e DALLINGER_NO_EGG_BUILD=1 \
  -e FLASK_OPTIONS='-h 0.0.0.0' \
  -e REDIS_URL=redis://dallinger_redis:6379 \
  -e DATABASE_URL=postgresql://dallinger:dallinger@dallinger_postgres/dallinger \
  -e PSYNET_DEVELOPER_MODE="${PSYNET_DEVELOPER_MODE:-}" \
  -v "${PSYNET_LOCAL_PATH}":/PsyNet \
  -v "${DALLINGER_LOCAL_PATH}":/dallinger \
  --add-host=host.docker.internal:host-gateway \
  "${EXPERIMENT_IMAGE}" \
  "$@"

# Note: the following
# -v ~/.ssh:/root/.ssh \
# only works for Mac.
